backend:
  name: test-repo
  local_backend: true

media_folder: "images"
public_folder: "/images"

site_url: https://daniel-thiessen.github.io/avery-portfolio
display_url: https://daniel-thiessen.github.io/avery-portfolio

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "_data/settings.yml"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string", default: "Avery Smith" }
          - { label: "Site Description", name: "site_description", widget: "text", default: "Showcase of artistic work and performances" }
  
  - name: "about"
    label: "About Section"
    files:
      - name: "about"
        label: "About"
        file: "_data/about.yml"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Profile Image", name: "profile_image", widget: "image" }
          - { label: "Bio", name: "bio", widget: "text" }
          - { label: "Long Bio", name: "long_bio", widget: "text" }

  - name: "current"
    label: "Current Work"
    folder: "_content/current"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Full Image", name: "full_image", widget: "image", required: false }
      - { label: "Video URL", name: "video", widget: "string", required: false, hint: "YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Order", name: "order", widget: "number", default: 1, value_type: "int" }

  - name: "choreography"
    label: "Choreography"
    folder: "_content/choreography"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Full Image", name: "full_image", widget: "image", required: false }
      - { label: "Video URL", name: "video", widget: "string", required: false, hint: "YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Order", name: "order", widget: "number", default: 1, value_type: "int" }

  - name: "projects"
    label: "Projects"
    folder: "_content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Full Image", name: "full_image", widget: "image", required: false }
      - { label: "Video URL", name: "video", widget: "string", required: false, hint: "YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Order", name: "order", widget: "number", default: 1, value_type: "int" }

  - name: "performances"
    label: "Performances"
    folder: "_content/performances"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Full Image", name: "full_image", widget: "image", required: false }
      - { label: "Video URL", name: "video", widget: "string", required: false, hint: "YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Order", name: "order", widget: "number", default: 1, value_type: "int" }

  - name: "contact"
    label: "Contact Information"
    files:
      - name: "contact"
        label: "Contact"
        file: "_data/contact.yml"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string", required: false }
          - label: "Social Media"
            name: "social_media"
            widget: "object"
            fields:
              - { label: "Instagram", name: "instagram", widget: "string", required: false }
              - { label: "Facebook", name: "facebook", widget: "string", required: false }
              - { label: "YouTube", name: "youtube", widget: "string", required: false }
              - { label: "Vimeo", name: "vimeo", widget: "string", required: false }
          - { label: "Enable Contact Form", name: "form_enabled", widget: "boolean", default: true }
