backend:
  name: github
  repo: daniel-thiessen/avery-portfolio
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site Config"
        name: "siteConfig"
        file: "js/config.js"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
